### ISSUE TITLE
Questions about horizontal scaling

### ISSUE THREAD

**Issue by liuyuanzhi-cn** [neondatabase/autoscaling#370]
1. Is it possible to set the number of pod replicas in neonvm ?
2. As this project describes, the project is "Postgres vertical autoscaling in k8s", but I still want to take the liberty to ask: Are there plans to provide automated scale-out functionality, similar to [Horizontal Pod Autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) in k8s.

**Comment by sharnoff** [comment]
Hi! thanks for your questions.

1. Not currently, no. Right now, VMs are more like a pod than a deployment — an individual `VirtualMachine` represents a single instance of a VM, possibly with multiple pods due to migrating that instance from one k8s node to another.
2. No such plans for HPA, no. TBH I don't see this happening, because it'd be a significant amount of work, and we have no need for it (at least, I think — I may be wrong!)

Happy to answer any other questions
