### ISSUE TITLE
Scheduler plugin's 'Score' results should be (weighted) random

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#412]
Deterministic scoring makes the system more fragile. We can improve this by making the score random in the range `[min score + 1, true score]`. The reason to make the floor just above the minimum score is because we use the minimum score for nodes where there isn't room, which shouldn't really ever be selected.

See also:

- #411

**Comment by fprasx** [comment]
# Goals
- place pods on nodes that have space
- prioritize slightly fuller nodes when selecting placement so that smaller
  nodes can be downscaled more quickly

# Current
- Nodes are given a score solely based on resource usage. The score is roughly
  min(% cpu free, % memory free). The issue is that this uniformly allocates pods
  on nodes, making downscaling more difficult due to not having small nodes. In
  other words, a nodes are equally good/bad choices to downscale.

# Ideas
- try to maintain two pools of nodes: one with nodes at relatively high usage
  and another with nodes at relatively low usage. (Maybe 60%/30%)
  - this could be achieved by multiplying scores by something like
    `scale(nodeUsage)` where scale is something like
    [this](https://www.desmos.com/calculator/ozeasx9knf)
    (a two-peaked distributin)

- bias against under-full nodes when scheduling
    - this could also be achieved by multiplying scores by something like
      `scale(nodeUsage)` where scale is something like
      [this](https://www.desmos.com/calculator/ur4tcp8hnm) (a sigmoid)

- assigning nodes a random score between (minimum score + 1, true score].
  The range is half open because we use the minimum score to indicate a pod
  should not be placed on a node.

- use `framework.CycleState` to store state about _all_ the nodes in the cluster.

**Comment by sharnoff** [comment]
Another idea re: randomness — we could use [`ScoreExtesnions.NormalizeScore`](https://pkg.go.dev/k8s.io/kubernetes/pkg/scheduler/framework#ScoreExtensions) to apply the randomness as a separate pass.
