### ISSUE TITLE
Docker rate limiting causes CI to fail

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#976]
When there's a lot of commits in a short period, we sometimes get rate limited by docker because we have unauthenticated image pulls in CI.

This causes CI to fail - and retrying doesn't help, because the issue is we're exceeding the rate limit :disappointed: 

It would be nice if this didn't happen, so CI didn't fail :)

```[tasklist]
- [ ] #814
- [ ] #975
```

**Comment by agadelshin** [comment]
Thoretically it's possible to use mirror.gcr.io instead of dockerhub for alpine/golang everywhere, they provide a cache from dockerhub for the most popular images - https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images, it's possible also to configure docker to use mirror automatically without changing Dockerfiles
